import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Provider from '../components/Provider'
import Sidebar from '../components/Sidebar'
import Newsfeed from '../components/Newsfeed'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    
      <body className={inter.className}>
        <div className='flex flex-row justify-between w-full h-screen bg-pink-800'>
          <div>
            <Sidebar/>
          </div>
      
          <Provider>
            {children}
          </Provider>

          <div className='hidden lg:block'>
            <Newsfeed/>
          </div>
         
        </div>
      
     </body>
    </html>
  )
}
