import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Provider from '../components/Provider'
import Sidebar from '../components/Sidebar'
import Newsfeed from '../components/Newsfeed'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    
      <body className={`${inter.className} bg-black`} >
        <div className='flex flex-row justify-between w-full h-full '>

          <aside className='h-screen sticky top-0'>
            <Sidebar/>
          </aside>
      
          <Provider>
            {children}
          </Provider>

          <aside className='hidden lg:block h-screen sticky top-0'>
            <Newsfeed/>
          </aside>
         
        </div>
      
     </body>
    </html>
  )
}
